<?php

namespace Repository;

/**
 * DomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomRepository extends \Doctrine\ORM\EntityRepository
{
}
