<?php

namespace Repository;

/**
 * GruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruntRepository extends \Doctrine\ORM\EntityRepository
{
}
