<?php

namespace Repository;

/**
 * KomunikacjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomunikacjaRepository extends \Doctrine\ORM\EntityRepository
{
    public function pobierzSlownik()
    {
        $query = $this->_em->createQuery("SELECT k FROM Entity\Komunikacja k ORDER BY k.nazwa ASC");
        $dane = $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        $temp = [];
        foreach ($dane as $d) {
            $temp[$d['id']] = $d['nazwa'];
        }

        return $temp;
    }
}
