<?php

namespace Repository;

/**
 * MiastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiastoRepository extends \Doctrine\ORM\EntityRepository
{
    public function pobierzSlownik()
    {
        $query = $this->_em->createQuery("SELECT m FROM Entity\Miasto m ORDER BY m.nazwa ASC");
        $dane = $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        $temp = [];
        foreach ($dane as $d) {
            $temp[$d['id']] = $d['nazwa'];
        }

        return $temp;
    }
}
