<?php

namespace Repository;

/**
 * MieszkanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MieszkanieRepository extends \Doctrine\ORM\EntityRepository
{
}
