<?php

namespace Repository;

/**
 * NieruchomoscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NieruchomoscRepository extends \Doctrine\ORM\EntityRepository
{
}
