<?php

namespace Repository;

/**
 * PowiatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PowiatRepository extends \Doctrine\ORM\EntityRepository
{
}
