<?php

namespace Repository;

/**
 * WojewodztwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WojewodztwoRepository extends \Doctrine\ORM\EntityRepository
{
}
